import React ,{useState} from 'react'

import Header from './Header.jsx'
import SortListWrap from './SortList.jsx'

export default (props)=>{
    const [group]=useState(
        {
            group:[
                {
                    id:'2',
                    content:'结伴同游',
                    img:'https://pic.qyer.com/icon/bbs/forums/2'
                },
                {
                    id:'3',
                    content:'签证',
                    img:'https://pic.qyer.com/icon/bbs/forums/3'
                },
                {
                    id:'148',
                    content:'保险',
                    img:'https://pic.qyer.com/icon/bbs/forums/148'
                    
                },
                {
                    id:'100',
                    content:'旅行购物',
                    img:'https://pic.qyer.com/icon/bbs/forums/100'
                },
                {
                    id:'121',
                    content:'穷游折扣',
                    img:'https://pic.qyer.com/icon/bbs/forums/121'
                },
                {
                    id:'154',
                    content:'睡遍全球',
                    img:'https://pic.qyer.com/icon/bbs/forums/154'
                },
                {
                    id:'94',
                    content:'邮轮',
                    img:'https://pic.qyer.com/icon/bbs/forums/94'
                },
                {
                    id:'62',
                    content:'航空',
                    img:'https://pic.qyer.com/icon/bbs/forums/62'
                },
                {
                    id:'33',
                    content:'自驾',
                    img:'https://pic.qyer.com/icon/bbs/forums/33'
                },
                {
                    id:'183',
                    content:'旅行视频',
                    img:'https://pic.qyer.com/icon/bbs/forums/183'
                },
                {
                    id:'22',
                    content:'旅行摄影',
                    img:'https://pic.qyer.com/icon/bbs/forums/22'
                },
                {
                    id:'40',
                    content:'户外运动',
                    img:'https://pic.qyer.com/icon/bbs/forums/40'
                },
                {
                    id:'88',
                    content:'潜水俱乐部',
                    img:'https://pic.qyer.com/icon/bbs/forums/88'
                },
                {
                    id:'122',
                    content:'带孩子旅行',
                    img:'https://pic.qyer.com/icon/bbs/forums/122'
                },
                {
                    id:'123',
                    content:'带父母旅行',
                    img:'https://pic.qyer.com/icon/bbs/forums/123'
                },
                {
                    id:'49',
                    content:'明信片',
                    img:'https://pic.qyer.com/icon/bbs/forums/49'
                },
                {
                    id:'184',
                    content:'路刻社',
                    img:'https://pic.qyer.com/icon/bbs/forums/184'
                },
                {
                    id:'188',
                    content:'Discovery探索频道',
                    img:'https://pic.qyer.com/icon/bbs/forums/188'
                }
            ],
            europe:[
                {
                    id:'112',
                    content:'环游欧洲',
                    img:'https://pic.qyer.com/icon/bbs/forums/112'
                },
                {
                    id:'14',
                    content:'法国/摩纳哥',
                    img:'https://pic.qyer.com/icon/bbs/forums/14'
                },
                {
                    id:'12',
                    content:'德国',
                    img:'https://pic.qyer.com/icon/bbs/forums/12'
                    
                },
                {
                    id:'15',
                    content:'瑞士/列支敦士登',
                    img:'https://pic.qyer.com/icon/bbs/forums/15'
                },
                {
                    id:'24',
                    content:'捷克/斯洛伐克/匈牙利',
                    img:'https://pic.qyer.com/icon/bbs/forums/24'
                },
                {
                    id:'18',
                    content:'西班牙/葡萄牙/安道尔',
                    img:'https://pic.qyer.com/icon/bbs/forums/18'
                },
                {
                    id:'26',
                    content:'希腊/塞浦路斯',
                    img:'https://pic.qyer.com/icon/bbs/forums/26'
                },
                {
                    id:'13',
                    content:'意大利/梵蒂冈/圣马力诺/马耳他',
                    img:'https://pic.qyer.com/icon/bbs/forums/13'
                },
                {
                    id:'16',
                    content:'英国/爱尔兰',
                    img:'https://pic.qyer.com/icon/bbs/forums/16'
                },
                {
                    id:'17',
                    content:'荷兰/比利时/卢森堡',
                    img:'https://pic.qyer.com/icon/bbs/forums/17'
                },
                {
                    id:'161',
                    content:'波兰/立陶宛/拉脱维亚/爱沙尼亚',
                    img:'https://pic.qyer.com/icon/bbs/forums/161'
                },
                {
                    id:'25',
                    content:'挪威/瑞典/芬兰/丹麦/冰岛',
                    img:'https://pic.qyer.com/icon/bbs/forums/25'
                },
                {
                    id:'158',
                    content:'俄罗斯/乌克兰/白俄罗斯',
                    img:'https://pic.qyer.com/icon/bbs/forums/158'
                },
                {
                    id:'160',
                    content:'外高加索三国',
                    img:'https://pic.qyer.com/icon/bbs/forums/160'
                },
                {
                    id:'162',
                    content:'土耳其',
                    img:'https://pic.qyer.com/icon/bbs/forums/162'
                },
                {
                    id:'159',
                    content:'东南欧地区',
                    img:'https://pic.qyer.com/icon/bbs/forums/159'
                },
                {
                    id:'25',
                    content:'欧洲交通',
                    img:'https://pic.qyer.com/icon/bbs/forums/109'
                }
            ],
            asia:[
                {
                    id:'58',
                    content:'环游亚洲',
                    img:'https://pic.qyer.com/icon/bbs/forums/58'
                },
                {
                    id:'57',
                    content:'日本',
                    img:'https://pic.qyer.com/icon/bbs/forums/57'
                },
                {
                    id:'156',
                    content:'韩国/朝鲜',
                    img:'https://pic.qyer.com/icon/bbs/forums/156'
                    
                },
                {
                    id:'52',
                    content:'台湾',
                    img:'https://pic.qyer.com/icon/bbs/forums/52'
                },
                {
                    id:'163',
                    content:'香港/澳门',
                    img:'https://pic.qyer.com/icon/bbs/forums/163'
                },
                {
                    id:'106',
                    content:'泰国',
                    img:'https://pic.qyer.com/icon/bbs/forums/106'
                },
                {
                    id:'108',
                    content:'马来西亚/文莱',
                    img:'https://pic.qyer.com/icon/bbs/forums/108'
                },
                {
                    id:'164',
                    content:'新加坡',
                    img:'https://pic.qyer.com/icon/bbs/forums/164'
                },
                {
                    id:'110',
                    content:'菲律宾',
                    img:'https://pic.qyer.com/icon/bbs/forums/110'
                },
                {
                    id:'175',
                    content:'柬埔寨',
                    img:'https://pic.qyer.com/icon/bbs/forums/175'
                },
                {
                    id:'107',
                    content:'越南',
                    img:'https://pic.qyer.com/icon/bbs/forums/107'
                },
                {
                    id:'176',
                    content:'老挝',
                    img:'https://pic.qyer.com/icon/bbs/forums/176'
                },
                {
                    id:'177',
                    content:'缅甸',
                    img:'https://pic.qyer.com/icon/bbs/forums/177'
                },
                {
                    id:'102',
                    content:'尼泊尔',
                    img:'https://pic.qyer.com/icon/bbs/forums/102'
                },
                {
                    id:'166',
                    content:'不丹',
                    img:'https://pic.qyer.com/icon/bbs/forums/166'
                },
                {
                    id:'111',
                    content:'印度尼西亚/东帝汶',
                    img:'https://pic.qyer.com/icon/bbs/forums/111'
                },
                {
                    id:'104',
                    content:'马尔代夫',
                    img:'https://pic.qyer.com/icon/bbs/forums/104'
                },
                {
                    id:'165',
                    content:'斯里兰卡',
                    img:'https://pic.qyer.com/icon/bbs/forums/165'
                },
                {
                    id:'103',
                    content:'印度/孟加拉',
                    img:'https://pic.qyer.com/icon/bbs/forums/103'
                },
                {
                    id:'59',
                    content:'伊朗',
                    img:'https://pic.qyer.com/icon/bbs/forums/59'
                },
                {
                    id:'169',
                    content:'巴基斯坦/阿富汗',
                    img:'https://pic.qyer.com/icon/bbs/forums/169'
                },
                {
                    id:'171',
                    content:'阿联酋/卡塔尔',
                    img:'https://pic.qyer.com/icon/bbs/forums/171'
                },
                {
                    id:'170',
                    content:'以色列',
                    img:'https://pic.qyer.com/icon/bbs/forums/170'
                },
                {
                    id:'172',
                    content:'西亚其他国家',
                    img:'https://pic.qyer.com/icon/bbs/forums/172'
                },
                {
                    id:'105',
                    content:'中亚各国',
                    img:'https://pic.qyer.com/icon/bbs/forums/105'
                },
                {
                    id:'167',
                    content:'蒙古',
                    img:'https://pic.qyer.com/icon/bbs/forums/167'
                },
                {
                    id:'51',
                    content:'中国内地',
                    img:'https://pic.qyer.com/icon/bbs/forums/51'
                }
            ],
            america:[
                {
                    id:'53',
                    content:'美国',
                    img:'https://pic.qyer.com/icon/bbs/forums/53'
                },
                {
                    id:'54',
                    content:'加拿大',
                    img:'https://pic.qyer.com/icon/bbs/forums/54'
                },
                {
                    id:'168',
                    content:'中美',
                    img:'https://pic.qyer.com/icon/bbs/forums/168'
                },
                {
                    id:'55',
                    content:'南美/南极',
                    img:'https://pic.qyer.com/icon/bbs/forums/55'
                }
            ],
            oceania:[
                {
                    id:'56',
                    content:'澳大利亚',
                    img:'https://pic.qyer.com/icon/bbs/forums/56'
                },
                {
                    id:'83',
                    content:'新西兰',
                    img:'https://pic.qyer.com/icon/bbs/forums/83'
                },
                {
                    id:'178',
                    content:'太平洋海岛',
                    img:'https://pic.qyer.com/icon/bbs/forums/178'
                }
            ],
            africa:[
                {
                    id:'86',
                    content:'北非地区',
                    img:'https://pic.qyer.com/icon/bbs/forums/86'
                },
                {
                    id:'173',
                    content:'东非地区',
                    img:'https://pic.qyer.com/icon/bbs/forums/173'
                },
                {
                    id:'174',
                    content:'非洲海岛',
                    img:'https://pic.qyer.com/icon/bbs/forums/174'
                },
                {
                    id:'60',
                    content:'非洲其他国家',
                    img:'https://pic.qyer.com/icon/bbs/forums/60'
                }
            ],
            onLine:[
                {
                    id:'99',
                    content:'穷游活动',
                    img:'https://pic.qyer.com/icon/bbs/forums/99'
                },
                {
                    id:'87',
                    content:'穷游er访谈',
                    img:'https://pic.qyer.com/icon/bbs/forums/87'
                },
                {
                    id:'157',
                    content:'穷游沙龙',
                    img:'https://pic.qyer.com/icon/bbs/forums/157'
                },
                {
                    id:'117',
                    content:'轻年计划',
                    img:'https://pic.qyer.com/icon/bbs/forums/117'
                },
                {
                    id:'185',
                    content:'城市漫步',
                    img:'https://pic.qyer.com/icon/bbs/forums/185'
                }
            ],
            backyard:[
                {
                    id:'20',
                    content:'海阔天空',
                    img:'https://pic.qyer.com/icon/bbs/forums/20'
                },
                {
                    id:'180',
                    content:'转让专区',
                    img:'https://pic.qyer.com/icon/bbs/forums/180'
                }
            ]
        }
    )
    return (
        <>
            <div>
                <Header title='穷游兴趣小组'></Header>
                <SortListWrap group={group.group}></SortListWrap>
            </div>

            <div>
                <Header title='穷游欧洲'></Header>
                <SortListWrap group={group.europe}></SortListWrap>
            </div>

            <div>
                <Header title='穷游亚洲'></Header>
                <SortListWrap group={group.asia}></SortListWrap>
            </div>

            <div>
                <Header title='穷游美洲'></Header>
                <SortListWrap group={group.america}></SortListWrap>
            </div>

            <div>
                <Header title='穷游大洋洲'></Header>
                <SortListWrap group={group.oceania}></SortListWrap>
            </div>

            <div>
                <Header title='穷游非洲'></Header>
                <SortListWrap group={group.africa}></SortListWrap>
            </div>

            <div>
                <Header title='线上线下'></Header>
                <SortListWrap group={group.onLine}></SortListWrap>
            </div>

            <div>
                <Header title='后院'></Header>
                <SortListWrap group={group.backyard}></SortListWrap>
            </div>
        </>
    )
}