import React,{useState} from 'react'

import {DetailWrap} from './detail.js'

import Header from 'pages/ask/header/Header.jsx'
import Img from './Img.jsx'
import Nav from './Nav.jsx'
import AskList from 'components/ask/AskList.jsx'

export default (props)=>{
    const [countries]=useState({
        14:[{
            id:'14',
            country:'JRPASS'
        },
        {
            id:'236',
            country:'签证'
        },
        {
            id:'215',
            country:'和服体验'
        },
        {
            id:'50',
            country:'温泉'
        },
        {
            id:'11186',
            country:'美食'
        },
        {
            id:'241',
            country:'行程'
        },
        {
            id:'238',
            country:'购物'
        },
        {
            id:'13',
            country:'关西'
        },
        {
            id:'189',
            country:'北海道'
        }],
        236:[{
            id:'14',
            country:'签证'
        },
        {
            id:'236',
            country:'自驾'
        },
        {
            id:'215',
            country:'行程'
        },
        {
            id:'50',
            country:'购物'
        },
        {
            id:'11186',
            country:'国家公园'
        },
        {
            id:'241',
            country:'租车'
        },
        {
            id:'238',
            country:'大学'
        },
        {
            id:'13',
            country:'纽约'
        },
        {
            id:'189',
            country:'拉斯维加斯'
        }],
        215:[{
            id:'14',
            country:'SPA'
        },
        {
            id:'236',
            country:'普吉岛'
        },
        {
            id:'215',
            country:'落地签'
        },
        {
            id:'50',
            country:'电话卡'
        },
        {
            id:'11186',
            country:'美食'
        },
        {
            id:'241',
            country:'酒吧'
        },
        {
            id:'238',
            country:'酒店'
        },
        {
            id:'13',
            country:'曼谷'
        },
        {
            id:'189',
            country:'清迈'
        }],
        50:[{
            id:'14',
            country:'购物'
        },
        {
            id:'236',
            country:'迪士尼'
        },
        {
            id:'215',
            country:'兰桂坊'
        },
        {
            id:'50',
            country:'签注'
        },
        {
            id:'11186',
            country:'美食'
        },
        {
            id:'241',
            country:'太平山'
        },
        {
            id:'238',
            country:'电影'
        },
        {
            id:'13',
            country:'八达通卡'
        },
        {
            id:'189',
            country:'酒店'
        }],
        11186:[{
            id:'14',
            country:'夜市'
        },
        {
            id:'236',
            country:'101'
        },
        {
            id:'215',
            country:'环岛'
        },
        {
            id:'50',
            country:'行程'
        },
        {
            id:'11186',
            country:'自由行'
        },
        {
            id:'241',
            country:'悠游卡'
        },
        {
            id:'238',
            country:'花莲'
        },
        {
            id:'13',
            country:'垦丁'
        },
        {
            id:'189',
            country:'台北'
        }],
        241:[{
            id:'14',
            country:'直升机'
        },
        {
            id:'236',
            country:'跳伞'
        },
        {
            id:'215',
            country:'皇后镇'
        },
        {
            id:'50',
            country:'签证'
        },
        {
            id:'11186',
            country:'自驾'
        },
        {
            id:'241',
            country:'行程'
        },
        {
            id:'238',
            country:'南岛'
        },
        {
            id:'13',
            country:'北岛'
        },
        {
            id:'189',
            country:'徒步'
        }],
        238:[{
            id:'14',
            country:'国家公园'
        },
        {
            id:'236',
            country:'自驾'
        },
        {
            id:'215',
            country:'落基山脉'
        },
        {
            id:'50',
            country:'签证'
        },
        {
            id:'11186',
            country:'极光'
        },
        {
            id:'241',
            country:'行程路线'
        },
        {
            id:'238',
            country:'购物'
        },
        {
            id:'13',
            country:'温哥华'
        },
        {
            id:'189',
            country:'枫叶'
        }],
        13:[{
            id:'14',
            country:'博物馆'
        },
        {
            id:'236',
            country:'英式下午茶'
        },
        {
            id:'215',
            country:'牡蛎卡'
        },
        {
            id:'50',
            country:'行程'
        },
        {
            id:'11186',
            country:'伦敦'
        },
        {
            id:'241',
            country:'牛津'
        },
        {
            id:'238',
            country:'城堡'
        },
        {
            id:'13',
            country:'哈利波特'
        },
        {
            id:'189',
            country:'剑桥'
        }],
        189:[{
            id:'14',
            country:'签证'
        },
        {
            id:'236',
            country:'罗马'
        },
        {
            id:'215',
            country:'威尼斯'
        },
        {
            id:'50',
            country:'米其林'
        },
        {
            id:'11186',
            country:'足球'
        },
        {
            id:'241',
            country:'美食'
        },
        {
            id:'238',
            country:'狂欢节'
        },
        {
            id:'13',
            country:'购物'
        },
        {
            id:'189',
            country:'佛罗伦萨'
        }]
    
    })
    const [keyword,setKeyword]=useState('')
    const [counry]=useState([
        {
            name:'日本',
            img:'https://pic.qyer.com/album/123/c8/1866577/index/680x450'
        },
        {
            name:'美国',
            img:'https://pic.qyer.com/album/user/2269/74/Q0tTSx0DZE0/index/680x450'
        },
        {
            name:'泰国',
            img:'https://pic.qyer.com/album/user/2584/28/Q0xdRhgPaU0/index/680x450'
        },
        {
            name:'香港',
            img:'https://pic.qyer.com/album/user/213/10/Q0hWQxoGYg/index/680x450'
        },
        {
            name:'台湾',
            img:'https://pic.qyer.com/album/user/1849/7/QEFRSxoAaEA/index/680x450'
        },
        {
            name:'新西兰',
            img:'https://pic.qyer.com/album/user/2130/73/Q0hWQh0EaU4/index/680x450'
        },
        {
            name:'加拿大',
            img:'https://pic.qyer.com/album/user/2579/13/Q0xSSxsEY0A/index/680x450'
        },
        {
            name:'英国',
            img:'https://pic.qyer.com/album/user/485/74/RUFQRR4GZg/index/680x450'
        },
        {
            name:'意大利',
            img:'https://pic.qyer.com/album/user/2068/18/Q0lTShsPZUA/index/680x450'
        }
    ])
    const getID=(keyword)=>{
        setKeyword(keyword)
    }
    return (
        <DetailWrap>
            <Header></Header>
            <Img name={counry[props.match.params.index].name} img={counry[props.match.params.index].img}></Img>
            <Nav type="detail" countries={countries[props.match.params.id]} sendId={getID}></Nav>
            <AskList url='/ask/ajaxapi/place/list' place_id={props.match.params.id} keyword={keyword}></AskList>
        </DetailWrap>
    )
}